stages:
  train_preprocessor:
    cmd: python train_preprocessor.py --data data/train.csv --output 
      models/preprocessor.pkl
    deps:
    - data/train.csv
    - train_preprocessor.py
    outs:
    - preprocessed_data/
  train:
    cmd: python train_preprocessor.py --data data/train.csv --params params.yaml
      --output models/model.pkl
    deps:
    - data/train.csv
    - train.py
    params:
    - train.C
    - train.penaltry
    - train.solver
    outs:
    - models/
